sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Amo020oaEn/8qZ7aqK4P/LFDTwjXfUvOKRv8mOFLJZbHJj8FsU2EtJZ73RnAMQc5iCEciSaPo7gEF3EkSvGYbcgId7JPw9NlfYxYF1xN3yHkAUpviBZS4jERZNhTi2b/KCR3jcqnXwfdiYQiLXk+K/ajeRSCHfGa6pdoPfHEVLiCJrh9H54d6JLKE/+eyflC0QwZAht6qq+ITezAT0RkNLVUhNxWtIIYI77I4hkTTkmdSehT9Y69B0AlbHGkreqpdxY9hCInLN6SBQ8my/2AoJKzZ00Wh5pqgI0bRAYcgRFnvXZWYCh5uQbegpr8gYpiV8GyU/Ja+Y3FcAy/bwpTCHAimLE2ksPIWdSd7iRaM8w69CL0ylMceYX6xtRpAnouaO3bh3NNVkM65EFecKAYlsSwhonLe9ojvZP/pJZveCMaYjZ/ve3L0QYisaSl+99MAOc05v1Qh5lcCNNivl2Qakk7r9fzPG2KtNVrHn+icE0RqVSj1oP09VI6OVJuijVBah6vmlBF/svt6ZadDUQVNJQLxKP6OexsETsc9rjrVz5OLbnU7+ih1xlW9ziRs8OofZtxqHLsrhTXSh9nVpzrsrzEa4PBS/VX8zVEoLh3HgOJqxH0zv+WnYW/NlDXdTjctodHlm5jej4RQa4Ufg2mu2a1NdrxsTxe2mPdRLB2a4E=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-History-of-Don-Quixote-Volume-2-Part-35_5938
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy